name: lingo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

ersion: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  salomon_bottom_bar: ^3.3.1
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  path_provider: ^2.0.11
  string_validator: ^0.3.0
  flutter_facebook_auth: ^4.1.2
  google_sign_in: ^5.2.4
  cloud_firestore: ^3.4.4
  path: any
  websafe_svg: ^2.1.2+3
  flutter_svg: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/google_btn.png
    - assets/images/fb_btn.png
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/cashir.jpg
    - assets/images/Robot.jpg
    - assets/svg/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
