// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwbRJxMScB1r6aL7WvfXCQZCa2NYQBYj0',
    appId: '1:567332270780:web:41e75fb5b076ba55c916b9',
    messagingSenderId: '567332270780',
    projectId: 'lingo-efd2f',
    authDomain: 'lingo-efd2f.firebaseapp.com',
    databaseURL: 'https://lingo-efd2f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lingo-efd2f.appspot.com',
    measurementId: 'G-4FJ2MKBT1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsoYExvXFj0qDfGb_NeIlp1xPSD-xMNGs',
    appId: '1:567332270780:android:9e8bd79d6d2d4a9ec916b9',
    messagingSenderId: '567332270780',
    projectId: 'lingo-efd2f',
    databaseURL: 'https://lingo-efd2f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lingo-efd2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvCPl8s2qcY7ctbM-Y6VNGioqsuunVvhE',
    appId: '1:567332270780:ios:055ef18dbbdf44b8c916b9',
    messagingSenderId: '567332270780',
    projectId: 'lingo-efd2f',
    databaseURL: 'https://lingo-efd2f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lingo-efd2f.appspot.com',
    iosClientId: '567332270780-tofvsa74ufsvc9ie0l4vd682d6u5npib.apps.googleusercontent.com',
    iosBundleId: 'com.lingo.lingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvCPl8s2qcY7ctbM-Y6VNGioqsuunVvhE',
    appId: '1:567332270780:ios:055ef18dbbdf44b8c916b9',
    messagingSenderId: '567332270780',
    projectId: 'lingo-efd2f',
    databaseURL: 'https://lingo-efd2f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lingo-efd2f.appspot.com',
    iosClientId: '567332270780-tofvsa74ufsvc9ie0l4vd682d6u5npib.apps.googleusercontent.com',
    iosBundleId: 'com.lingo.lingo',
  );
}
