name: iOS - Android App Build
on:
  push:
    branches:
      - main
jobs:
  flutter_test:
    name: Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          flutter pub get
          flutter analyze
          # flutter test # we comment this to avoid serious nithmare and build app first to see :)

  build:
    name: Build iOS and Android
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          channel: "stable"
          architecture: x64
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --debug --split-per-abi
#      - run: |
#          pod install
#          pod update
#          flutter build ios --no-codesign
#          cd build/ios/iphoneos
#          mkdir Payload
#          cd Payload
#          ln -s ../Runner.app
#          cd ..
#          zip -r app.ipa Payload

      - name: Publish iOS, Android Release
        uses: ncipollo/release-action@v1
        with:
#          artifacts: "build/app/outputs/apk/debug/*x86_64-debug.apk, build/ios/iphoneos/app.ipa"
          artifacts: "build/app/outputs/apk/debug/*x86_64-debug.apk,"
          tag: v1.0.${{ github.run_number }}
          token: ${{secrets.LINGO}}